name: colobot-pz # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: ColoBot Adventure
summary: Challenge yourself and your friends in CodeBattles. # 79 char long summary
description: |
  Code Battles' where programming prowess meets strategic combat! 
  Engage in thrilling battles of wit and skill as you command a team of robotic minions using your coding expertise. 

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  colobot-pz:
    command: bin/colobot-pz-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  colobot-pz:
    plugin: dump
    source: .
    organize:
      colobot-pz-bin: bin/
